server:
  port: 8401

spring:
  application:
    name: aservice-rbac
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://123.56.169.21:3306/linnadb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: linna
    password: d%r2Tz08
    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    inetutils:
#      preferredNetworks:
#        - 192.168
#      ignored-interfaces:
#        - .*VirtualBox.*

# debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://root:root@peer1:8761/eureka/eureka/,http://root:root@peer2:8761/eureka/eureka/,http://root:root@peer3:8761/eureka/eureka/

ribbon:
  eager-load:
    enabled: true
    clients: aservice-sms

feign:
  okhttp:
    enabled: true

logging:
  level:
    com.zimug.dongbb.cloud.aservice.rbac.feign.SmsService: debug


#aservice-rbac:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.zimug.dongbb.cloud.aservice.rbac.config.MyLoadBanlanceRule

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: refresh,health

user:
  init:
    password: Abcd1234
